### ISSUE TITLE
Toolkit won't import in Python 3.12

### ISSUE THREAD

**Issue by fayvor** [ibm-granite/granite-tsfm#118]
When I run:
`from tsfm_public import toolkit`

I get:
```
RuntimeError: Failed to import tsfm_public.toolkit because of the following error (look up to see its traceback):
No module named 'distutils'
```
This is because `distutils` has been removed from Python 3.12.

The `distutils` package is being imported [here in toolit/utils.py.](https://github.com/ibm-granite/granite-tsfm/blob/c2f07f2604b9729c18be21f6a4da26da1e72b6c2/tsfm_public/toolkit/util.py#L8) to get `strtobool`.

[This SO answer](https://stackoverflow.com/a/77942057/321674) proposes an alternative to `strtobool`.

Please update `tsfm_public.toolkit` to remove usages of `distutils`.

**Comment by wgifford** [comment]
Hi @fayvor 
In a clean 3.12.4 python environment, with only:

```
Package    Version
---------- -------
pip        24.2
setuptools 72.1.0
wheel      0.43.0

```
I was able to `pip install .` from cloned repo and import without any issue. Can you tell me what python version you are using and what version of `setuptools` is installed?

**Comment by fayvor** [comment]
Hi @wgifford,

Here are my versions:
```
(.venv) fayvor@MacBook-Pro granite-code-cookbook % python --version 
Python 3.12.4
(.venv) fayvor@MacBook-Pro granite-code-cookbook % pip show setuptools|grep Version
Version: 73.0.1
```

**Comment by fayvor** [comment]
I installed `tsfm_public` like this:
```
# Install the tsfm library
! pip install "tsfm_public[notebooks] @ git+ssh://git@github.com/ibm-granite/granite-tsfm.git"
```

**Comment by fayvor** [comment]
It seems to be working now; something has changed since I filed this. Maybe I didn't actually have setuptools installed; I'm not sure.

Anyway, thanks for responding! I'm good for now.

**Comment by fayvor** [comment]
I will put an instruction in the notebook to install setuptools.

**Comment by wgifford** [comment]
It's listed in the `pyproject.toml` in the `build-system` section. Does this cover it?

**Comment by wgifford** [comment]
I removed `tsfm_public` and `setuptools` from my environment, and reinstalled `tsfm_public` -- `setuptools` was reinstalled.

**Comment by ssiegel95** [comment]
@wgifford [this line](https://github.com/ibm-granite/granite-tsfm/blob/v0.2.8/tsfm_public/toolkit/util.py#L8) should still fail with python 3.12, though.

We'd have to do 

```
from setuptools.dist import strtobool
```

instead I think.

**Comment by fayvor** [comment]
It fails again for me, with the same versions of python and setuptools as above. My steps were:

Start with a venv using Python 3.12.4
```
# Install the tsfm library
pip install "tsfm_public[notebooks] @ git+ssh://git@github.com/ibm-granite/granite-tsfm.git"

from tsfm_public import toolkit
...
RuntimeError: Failed to import tsfm_public.toolkit because of the following error (look up to see its traceback):
No module named 'distutils'
```

**Comment by fayvor** [comment]
I tried it another way and it works:

```
fayvor@MacBook-Pro granite-code-cookbook % python -m venv .venv
fayvor@MacBook-Pro granite-code-cookbook % source .venv/bin/activate
(.venv) fayvor@MacBook-Pro granite-code-cookbook % pip install "tsfm_public[notebooks] @ git+ssh://git@github.com/ibm-granite/granite-tsfm.git"
(.venv) fayvor@MacBook-Pro granite-code-cookbook % python -c "from tsfm_public import toolkit"
INFO:p-31754:t-8635339328:config.py:<module>:PyTorch version 2.2.2 available.
...

So, it may have something to do with running within the notebook. Maybe the jupyter dependencies that get installed?

**Comment by wgifford** [comment]
> @wgifford [this line](https://github.com/ibm-granite/granite-tsfm/blob/v0.2.8/tsfm_public/toolkit/util.py#L8) should still fail with python 3.12, though.
> 
> We'd have to do
> 
> ```
> from setuptools.dist import strtobool
> ```
> 
> instead I think.

In my environment, both work, but we can switch to the `setuptools.dist` if that is more correct.

**Comment by fayvor** [comment]
> we can switch to the setuptools.dist if that is more correct.

Let me test that.

**Comment by wgifford** [comment]
> fayvor@MacBook-Pro granite-code-cookbook % python -m venv .venv
> fayvor@MacBook-Pro granite-code-cookbook % source .venv/bin/activate
> (.venv) fayvor@MacBook-Pro granite-code-cookbook % pip install "tsfm_public[notebooks] @ git+ssh://git@github.com/ibm-granite/granite-tsfm.git"
> (.venv) fayvor@MacBook-Pro granite-code-cookbook % python -c "from tsfm_public import toolkit"
> INFO:p-31754:t-8635339328:config.py:<module>:PyTorch version 2.2.2 available.

If I follow steps like the above it works fine for me. If I start jupyter from within .venv, I also have no issues.

**Comment by ssiegel95** [comment]
When I do a clean install in new python3.12 environment I end up with

```
(py312) ➜  granite-tsfm git:(main) pip list | grep tool
fonttools                 4.53.1
prompt_toolkit            3.0.47
setuptools                73.0.1
```

So setuptools is there (by virtue of the build dependency in the pyproject.toml file) but not distools (which is no longer part of the standard python lib in >=3.12). Perhaps you had manually installed distutils (which is still available) at some piint? What I don't get is why the tests are passing. I guess we're not covering that line since we don't invoke the notebooks.

**Comment by fayvor** [comment]
It appears that the installation of `granite-tsfm` is not always installing setuptools for me. But when I have setuptools installed, things work fine.

```
(.venv) fayvor@MacBook-Pro granite-code-cookbook % pip install ../granite-tsfm
Processing /Users/fayvor/Dev/granite-tsfm
...
Successfully built tsfm_public
Installing collected packages: pytz, mpmath, xxhash, wrapt, urllib3, tzdata, typing-extensions, tqdm, threadpoolctl, sympy, safetensors, regex, pyyaml, numpy, networkx, multidict, MarkupSafe, joblib, idna, fsspec, frozenlist, filelock, dill, charset-normalizer, certifi, attrs, aiohappyeyeballs, yarl, scipy, requests, pyarrow, pandas, multiprocess, jinja2, deprecated, aiosignal, torch, scikit-learn, huggingface-hub, aiohttp, tokenizers, accelerate, transformers, datasets, tsfm_public
Successfully installed MarkupSafe-2.1.5 accelerate-0.33.0 aiohappyeyeballs-2.4.0 aiohttp-3.10.5 aiosignal-1.3.1 attrs-24.2.0 certifi-2024.7.4 charset-normalizer-3.3.2 datasets-2.21.0 deprecated-1.2.14 dill-0.3.8 filelock-3.15.4 frozenlist-1.4.1 fsspec-2024.6.1 huggingface-hub-0.24.6 idna-3.8 jinja2-3.1.4 joblib-1.4.2 mpmath-1.3.0 multidict-6.0.5 multiprocess-0.70.16 networkx-3.3 numpy-1.26.4 pandas-2.2.2 pyarrow-17.0.0 pytz-2024.1 pyyaml-6.0.2 regex-2024.7.24 requests-2.32.3 safetensors-0.4.4 scikit-learn-1.5.1 scipy-1.14.1 sympy-1.13.2 threadpoolctl-3.5.0 tokenizers-0.19.1 torch-2.2.2 tqdm-4.66.5 transformers-4.44.2 tsfm_public-0.2.8 typing-extensions-4.12.2 tzdata-2024.1 urllib3-1.26.19 wrapt-1.16.0 xxhash-3.5.0 yarl-1.9.4

(.venv) fayvor@MacBook-Pro granite-code-cookbook % pip show setuputils
WARNING: Package(s) not found: setuputils
```

**Comment by ssiegel95** [comment]
okay, I think what's happening is that setuptools mirrors the distutils api:

```
(py312) ➜  toolkit git:(main) python
Python 3.12.4 (main, Jun  7 2024, 00:00:00) [GCC 14.1.1 20240607 (Red Hat 14.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distutils
>>> distutils.__file__
'/home/stus/py312/lib64/python3.12/site-packages/setuptools/_distutils/__init__.py'
```

**Comment by wgifford** [comment]
@ssiegel95 I also tried in a clean environment -- as far as I can tell, imports for distutils.util is being redirected to setuptools.

**Comment by ssiegel95** [comment]
our messages just crossed, yes.

**Comment by ssiegel95** [comment]
I agree with @fayvor that we should make setuptools (any version matching the build requirements) an explicit requirement. another option is to just life the implementation of strtobool which is fairly trivial.

**Comment by fayvor** [comment]
> What I don't get is why the tests are passing. I guess we're not covering that line since we don't invoke the notebooks.

I think `setuptools` provides `distutils`. Maybe via an alias? Not sure. But look at this:

```
fayvor@MacBook-Pro test % python -m venv .venv
fayvor@MacBook-Pro test % source .venv/bin/activate                        
(.venv) fayvor@MacBook-Pro test % python -c "import distutils"
...
ModuleNotFoundError: No module named 'distutils'
(.venv) fayvor@MacBook-Pro test % pip install setuptools      
...
Successfully installed setuptools-73.0.1
(.venv) fayvor@MacBook-Pro test % python -c "import distutils"
(.venv) fayvor@MacBook-Pro test % 
```

**Comment by fayvor** [comment]
> okay, I think what's happening is that setuptools mirrors the distutils api:

@ssiegel95 that would explain it.

**Comment by fayvor** [comment]
However you guys decide to go forward with supporting Python 3.12, this is no longer a blocker for me. 

Thank you!!

**Comment by wgifford** [comment]
Since it is only the `strtobool` function that is needed, we may just include the implementation directly.
