### ISSUE TITLE
index error when there are fewer than 2 rows in a group dataframe

### ISSUE THREAD

**Issue by chandrakreddy** [ibm-granite/granite-tsfm#128]
`tsfm_public/toolkit/dataset.py:879` will have an index error if there are fewer than 2 rows in the input dataframe in case of timestamp_column not being None. in this case, simply return the data frame.

**Comment by wgifford** [comment]
@chandrakreddy if there are fewer than two rows in the input dataframe (or any split of the dataframe), I am seeing the error here:

```
tsfm_public/toolkit/dataset.py:1117: in ts_padding
    period = df.iloc[1][timestamp_column] - df.iloc[0][timestamp_column]
```

Period of the data cannot be estimated without two or more samples. In this case, we fill timestamp column with None -- resulting dataset will have NaT as the timestamp. If you have ideas of a different strategy, please let me know.

**Comment by wgifford** [comment]
This was addressed in a previous PR. Closing for now.
