### ISSUE TITLE
plot_prediction throw ValueError while using Exogenous Infusion

### ISSUE THREAD

**Issue by omriargaman** [ibm-granite/granite-tsfm#134]
When running plot_predictions with Exogenous Infusion (as provided on example notebook) i get an error message:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-28-e9bd78d817f3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 plot_predictions(
      2     model=finetune_forecast_trainer.model,
      3     dset=test_dataset,
      4 
      5     plot_dir=os.path.join(OUT_DIR, "bike_sharing"),

9 frames
[/usr/local/lib/python3.10/dist-packages/tsfm_public/models/tinytimemixer/modeling_tinytimemixer.py](https://localhost:8080/#) in forward(self, base_forecasts, past_values, future_values)
    696 
    697         if self.exogenous_channel_count > 0 and future_values is None:
--> 698             raise ValueError("future_values cannot be none when we have exogenous channels.")
    699 
    700         if self.exogenous_channel_count > 0:

ValueError: future_values cannot be none when we have exogenous channels.

although the dataset test_dataset holds future_values

**Comment by wgifford** [comment]
Please try the latest from main. This will be included in the next release.

**Comment by wgifford** [comment]
Closing for now, please reopen if there is an issue.
