### ISSUE TITLE
metadata should be limited to the context and forecast windows

### ISSUE THREAD

**Issue by chandrakreddy** [ibm-granite/granite-tsfm#154]
in "masking" branch, metadata currently spans the entire dataframe. it should be limited to context and forecast windows.
`            if self.metadata_columns:
                ret["metadata"] = self.data_df[self.metadata_columns].values[
                    time_id : time_id + self.context_length + self.prediction_length
                ]`

**Comment by wgifford** [comment]
Yes... should have definitely been restricted to the appropriate context window + prediction window. Should be addressed now.
