### ISSUE TITLE
optimal_lr_finder

### ISSUE THREAD

**Issue by Killer3048** [ibm-granite/granite-tsfm#155]
optimal_lr_finder is not in the tsfm_public library, not even in the github repository, but in jupyter for exog start  optimal_lr_finder used .-.

**Comment by wgifford** [comment]
Hi @Killer3048 please point me to which notebook you are using.

I don't see `optimal_lr_finder` in: https://github.com/ibm-granite/granite-tsfm/blob/main/notebooks/tutorial/ttm_with_exog_tutorial.ipynb

However, it will be made available once we merge: https://github.com/ibm-granite/granite-tsfm/tree/ttm_v2_release

**Comment by Killer3048** [comment]
Oh sorry. I just check this version with new tree... 
thanks
