### ISSUE TITLE
How to change the scaler when using the Tiny Time Mixer (TTM)

### ISSUE THREAD

**Issue by kujhin** [ibm-granite/granite-tsfm#180]
I am implementing TTM by following the tutorial of the tsfm_public package.
However, during evaluation, in the part where I call:

finetune_forecast_trainer.evaluate(test_dataset)

it appears that the eval_loss value is currently calculated based on the standard scaler. However, I would like to know the MSE value on the original scale. Could you provide guidance on how to achieve this?

**Comment by wgifford** [comment]
For inverse scaling, you can use the forecasting pipeline, which makes use of the time series preprocessor for inverse scaling. Some examples can be found here: https://github.com/ibm-granite-community/granite-timeseries-cookbook/blob/main/recipes/Time_Series/Preprocessor_Use_and_Performance_Evaluation.ipynb

**Comment by kujhin** [comment]
Thank you for your kind answer. I have one more question - could you show me how the get_datasets function is structured? When I tried to use it with my data, the length of train_dataset came out as 1, so I'd like to check how this function works.
