### ISSUE TITLE
BaseForecastDFDataset with negative index

### ISSUE THREAD

**Issue by mdruiter** [ibm-granite/granite-tsfm#181]
Indexing `someset.datasets[0]` with a negative index does weird things. I would expect to count from the back as usual. Try `someset.datasets[0][-600]` for example.

As far as I can see, `BaseForecastDFDataset.__getitem__` does not take negative values into account but just blindly adds `self.context_length`... This also causes `timestamp` to get out of sync (for very negative values).

**Comment by wgifford** [comment]
Thank you for the issue!

Indeed, when you directly index into the base datasets you may get some undesirable behavior. I made a few changes in this branch: https://github.com/ibm-granite/granite-tsfm/tree/issue_181

Can you see if this guards against the issues you are seeing?

**Comment by mdruiter** [comment]
Looks good!
