### ISSUE TITLE
Does demo support multivariate input single output?

### ISSUE THREAD

**Issue by zmce2018** [ibm-granite/granite-tsfm#19]
Thank you so much for providing an easy-to-follow demo and notebook. I have seen the example given on multivariate input and multivariate output forecasting. I wonder if this module supports multivariate input and single output.

For instance, using "HUFL","HULL","MUFL","MULL","LUFL","LULL","OT" as input and predict "MUFL" since we only care about "MUFL"?

**Comment by Scott534** [comment]
yes, just add 'prediction_channel_indices' to your PatchTSMixerConfig.
for example:
```
config = PatchTSMixerConfig(
        context_length=context_length,
        prediction_length=forecast_horizon,
        patch_length=patch_length,
        num_input_channels=len(forecast_columns2),
        patch_stride=patch_stride,
        d_model=d_model,
        num_layers=3,
        expansion_factor=3,
        dropout=0.7,
        head_dropout=0.6,
        mode="common_channel",
        scaling="std",
        prediction_channel_indices=forecast_channel_indices,
    )
```

**Comment by Akhim-yun** [comment]
Hello, I would like to ask if the ttm model supports multi-variable input?

**Comment by wgifford** [comment]
@Akhim-yun Yes, it does support multivariate input.

If you fine tune the TTM model, you will want to try `decoder_mode="mix_channel"`.

**Comment by Akhim-yun** [comment]
> @Akhim-yun Yes, it does support multivariate input.
> 
> If you fine tune the TTM model, you will want to try `decoder_mode="mix_channel"`.

Hello, thanks for your reply. I found decoder_mode="mix_channel", but I would like to ask if there is a specific example to do multi-variable input. I don’t know what to do next. Thank you!

**Comment by Akhim-yun** [comment]
> @Akhim-yun Yes, it does support multivariate input.
> 
> If you fine tune the TTM model, you will want to try `decoder_mode="mix_channel"`.

I mean using TTM to input "HUFL","HULL","MUFL","MULL","LUFL","LULL" to predict "OT"

**Comment by wgifford** [comment]
Hi @Akhim-yun for the exogenous case you mention above -- this will be supported once we release some additional functionality. I expect that to be within a few weeks.

Thanks!
