### ISSUE TITLE
Support for Non-Continuous Time Points and Custom Frequency Mapping in Dataset

### ISSUE THREAD

**Issue by IsaacWang-Ch** [ibm-granite/granite-tsfm#200]
### Description:
I have the following concerns and questions about handling datasets with non-continuous timestamps and customizing frequency mappings:

1. **Handling Non-Continuous Timestamps**:
   - If the dataset contains time points that are not continuous (e.g., gaps between specific periods), how will the model handle such data?
   - Example: I have `n` days of data, each spanning from 8:00 AM to 6:00 PM with a 1-hour interval. Can I concatenate these days into a single dataset and train the model effectively, even though there are gaps between the days (e.g., no data from 4:00 PM to 8:00 AM)?

2. **Customizing Frequency Mapping**:
   - Can the `DEFAULT_FREQUENCY_MAPPING` be modified to support additional step intervals, such as 30 minutes or 15 minutes? 

Looking forward to understanding the best practices or potential adjustments required in the implementation.

**Comment by wgifford** [comment]
Hi. Thank you for your interest in Granite-TSFM.
1. The model itself handles sequences of values, the individual timestamps are not passed as input to the model. They come into play only during: 1) estimating the frequency (e.g., for the frequency token), and 2) if you use the forecasting pipeline, the timestamps for the predictions will be created based on the frequency and the last timestamp of the context window. All the pretrained models and the benchmarking were conducted on datasets with uniformly sampled timestamps. You can try simply concatenating the data you have (so there will be missing timestamps) and see how it performs. Additionally, if you have longer episodic data you can tag each episode with a unique id and pass the information as an id column when constructing the time series preprocessor, dataset, pipeline, etc. This approach can be useful for sensor data collected from separate runs of a process.
2. For a customized frequency mapping, you can pass a dictionary when instantiating the time series preprocessor using the `frequency_mapping` argument. The value passed should be a dictionary with string keys and integer values. If you use the frequency token with a new mapping, you will need to pretrain the model to take the new mapping into account.

**Comment by IsaacWang-Ch** [comment]
@wgifford Thank you for your reply! Closing the issue.
