### ISSUE TITLE
Confuse about the output.predictions

### ISSUE THREAD

**Issue by eromoe** [ibm-granite/granite-tsfm#29]
There are 4 forecast labels set up with `forecast_horizon = 5`.
The strange thing is that the output `len(output.predicals)` is 4 and `output.predictions[0].shape` is `(168000, 5, 4)`

I think `(168000, 5, 4)` means predict 5 forecasts for 4 labels on 168000 time_id. 
If my assuption is ture, why `len(output.predicals)` is 4 , what is the extra 4 dimensions stands for ?

**Comment by wgifford** [comment]
@eromoe Could you provide a reference to an example (maybe you are referring to a particular notebook)?

**Comment by eromoe** [comment]
It's `patch_tsmixer_getting_started.ipynb` ,  I changed the input data / target and forecast horizon . 


```
for p in output.predictions:
    print(p.shape)
```

(169500, 5, 4)
(169500, 4, 3, 48)
(169500, 1, 4)
(169500, 1, 4)

This make me confused .

**Comment by davidkurtenb** [comment]
Within the output = trainer.predict(test_dataset), where are the predictions for the target value?

**Comment by wgifford** [comment]
> ```
> for p in output.predictions:
>     print(p.shape)
> ```
> 
> (169500, 5, 4) 
^ Predictions of the target variables

> (169500, 4, 3, 48) 
^ Last hidden state

> (169500, 1, 4) 
^ 
loc parameter

> (169500, 1, 4)
^ 
scale parameter

These parameters are are defined in https://github.com/huggingface/transformers/blob/main/src/transformers/models/patchtsmixer/modeling_patchtsmixer.py#L1748

I believe loss and hidden_states are not included because `output_hidden_states = False` and `return_loss=False`.

**Comment by wgifford** [comment]
> Within the output = trainer.predict(test_dataset), where are the predictions for the target value?

It would be `output.predictions[0]`.

**Comment by wgifford** [comment]
Closing for now, let me know if you have more questions.
