### ISSUE TITLE
Help needed. Support for python3.11

### ISSUE THREAD

**Issue by DhavalRepo18** [ibm-granite/granite-tsfm#57]
Any idea when will support for python 3.11 is going to be available?

**Comment by DhavalRepo18** [comment]
![image](https://github.com/ibm-granite/granite-tsfm/assets/47201243/15ba0d1b-c995-4e12-b85d-cb1d1b7e1abe)

**Comment by DhavalRepo18** [comment]
![image](https://github.com/ibm-granite/granite-tsfm/assets/47201243/b2415f66-f016-472f-bc6c-ed749aa86ef8)

Can you please update the .md file.

**Comment by wgifford** [comment]
Closing -- please reopen if any issues remain.
