### ISSUE TITLE
How to use GPUs for inference?

### ISSUE THREAD

**Issue by jcrowthe** [ibm-granite/granite-tsfm#99]
Hey, it is unclear how to use a GPU during inference. Attached is an example notebook which I've assembled for inference, using the existing tutorials. When using `TimeSeriesForecastingPipeline` for a forecast, the following warning is always printed:

```
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
```

I have tried adding the following to the notebook, after finding something similar in other notebooks:
```
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
```

And as can be seen in the attached notebook, `print(device)` produces `cuda`. 

Notably, I have also attempted to specify the GPU device ID as well, such as `device = torch.device('cuda:0')` but produces the same warning.

How can I specify a GPU to be used during inference?

Notebook: https://colab.research.google.com/drive/1Ex88gwSGAYspRml6t_0ws93rShN24t3B?usp=sharing

**Comment by wgifford** [comment]
@jcrowthe Thanks for the issue.

I think if you pass `device` in the TimeSeriesForecastingPipeline call that device will be used:
```
forecast_pipeline = TimeSeriesForecastingPipeline(
    model=zeroshot_model,
    timestamp_column="date",
    id_columns=[],
    target_columns=["HUFL", "HULL", "MUFL", "MULL", "LUFL", "LULL", "OT"],
    freq="15m",
    feature_extractor=tsp,
    explode_forecasts=False,
    inverse_scale_outputs=True,
    device=device
)
```

Please try it and let me know what you find. We may need to add some additional functionality during dataset creation.
